In [17]:
pip install lingua-language-detector

Collecting lingua-language-detector
  Downloading lingua_language_detector-2.2.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (31 kB)
Downloading lingua_language_detector-2.2.0-cp314-cp314-macosx_11_0_arm64.whl (172.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.5/172.5 MB 1.1 MB/s  0:01:59 eta 0:00:01[36m0:00:05m
Installing collected packages: lingua-language-detector
Successfully installed lingua-language-detector-2.2.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import sys, subprocess
for pkg in ["selenium", "pandas", "openpyxl", "langdetect"]:
    try:
        __import__(pkg.replace("-","_"))
        print(f"✅ {pkg}")
    except ImportError:
        subprocess.run([sys.executable,"-m","pip","install",pkg], check=True)
        print(f"✅ {pkg} installé")
print("Prêt.")

✅ selenium
✅ pandas
✅ openpyxl
✅ langdetect
Prêt.

In [1]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-casablanca-city-center.html?auth_success=1#tab-reviews"
HOTEL_NAME = "Ibis Casablanca City Center"
HOTEL_CITY = "Casablanca"
MAX_PAGES = 400
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            # Scroll vers le bouton
            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            # Clic
            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            # Poll 30s
            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=400):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Casablanca City Center (Casablanca)
   📄 Page 1  (0 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (9 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (19 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (29 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (39 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (49 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (59 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (69 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (78 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (88 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (98 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (108 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (118 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (128 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (138 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (148 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (158 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (168 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (178 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (188 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (198 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (208 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (218 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (228 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (238 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (248 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (258 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (268 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (278 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (288 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (298 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (308 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (318 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (328 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (338 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (348 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (358 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (368 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (378 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (388 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (398 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (408 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (418 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (428 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (438 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (448 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (458 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 48  (468 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (478 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (488 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 51  (498 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (508 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (518 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (528 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (538 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (548 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (558 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (568 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (578 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (588 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (598 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (608 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (618 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (628 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (638 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (648 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (658 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (668 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (678 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 70  (688 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (698 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (708 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (718 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (728 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (738 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (748 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (758 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (768 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (778 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (788 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (798 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (808 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (818 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (828 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (838 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (848 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (858 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (868 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (878 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (888 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (898 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (908 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (918 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (928 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (938 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (948 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (958 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (968 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (978 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (988 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (998 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1008 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1018 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1028 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1038 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1048 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1058 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1068 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1078 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1088 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1098 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1108 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1118 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1128 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1138 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1148 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1158 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 118  (1168 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1178 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1187 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1197 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1207 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 123  (1217 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 124  (1226 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1236 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 126  (1246 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 127  (1255 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 128  (1265 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 129  (1273 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 130  (1283 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 131  (1293 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 132  (1303 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 133  (1313 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 134  (1323 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 135  (1333 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 136  (1343 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3

In [2]:
df.head()

,source,hotel_name,hotel_city,reviewer_name,nationality,rating,review_title,review_text,positive_comment,negative_comment,publication_date,stay_date,trip_type,language
0,booking.com,Ibis Casablanca City Center,Casablanca,Hermann,France,8.0,Très bon emplacement pour visiter Casablanca,Super emplacement. Personnel très sympathique....,Super emplacement. Personnel très sympathique....,"Oreillers à changer, car déformés. Je pense qu...",Commentaire envoyé le 20 avril 2026,avril 2026,Famille,french
1,booking.com,Ibis Casablanca City Center,Casablanca,Linda,Espagne,8.0,Séjour Casablanca,Personnel à la réception très courtois et atte...,Personnel à la réception très courtois et atte...,Manque de fruits et fromage au petit déjeuner,Commentaire envoyé le 12 avril 2026,avril 2026,Voyageur individuel,french
2,booking.com,Ibis Casablanca City Center,Casablanca,Ifriquine,Maroc,9.0,Fabuleux,Le personnel est tres sympa Rien,Le personnel est tres sympa,Rien,Commentaire envoyé le 9 avril 2026,avril 2026,Famille,french
3,booking.com,Ibis Casablanca City Center,Casablanca,Mohamed,Maroc,7.0,Bon séjour,Bon séjour rapide RAS,Bon séjour rapide,RAS,Commentaire envoyé le 9 avril 2026,avril 2026,Voyageur individuel,french
4,booking.com,Ibis Casablanca City Center,Casablanca,Aboubakr,France,9.0,sympa,la proximité de tous le prix la propreté \nle ...,la proximité de tous le prix la propreté \nle ...,le parquet de la chambre,Commentaire envoyé le 7 avril 2026,avril 2026,Voyageur individuel,french

In [4]:
df.shape

(4000, 14)

In [3]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-casablanca-sidi-maarouf.html?auth_success=1#tab-reviews"
HOTEL_NAME = "Ibis Casablanca Sidi Maarouf"
HOTEL_CITY = "Casablanca"
MAX_PAGES = 90
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Casablanca Sidi Maarouf (Casablanca)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Suivant'
      ⚠️  Clic normal échoué : Message: element click intercepted: Element <button aria-label="Suivant" type="button" class="de576f5064 b46cd7aad7 e19e62abbe c295306d66 c7a901b0e7 fe50231b86 b6ea2e8677 a6b947b3b5 bfafa531ed ae7f05552f e7f2b1a356">...</button> is not clickable at point (1141, 325). Other element would receive the click: <div class="da09d852f1">...</div>
  (Session info: chrome=147.0.7727.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementclickinterceptedexception
Stacktrace:
0   chromedriver                        0x00000001054cbabc cxxbridge1$str$ptr + 3192864
1   chromedriver                        0x00000001054c3a8c cxxbridge1$str$ptr + 3160048
2   chromedriver                        0x0000000104f8f7c0 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 75348
3   chromedriver                        0x0000000104fdd14c _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 393184
4   chromedriver                        0x0000000104fdb674 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 386312
5   chromedriver                        0x0000000104fd93dc _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 377456
6   chromedriver                        0x0000000104fd877c _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 374288
7   chromedriver                        0x0000000104fce8dc _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 333680
8   chromedriver                        0x0000000104fce358 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332268
9   chromedriver                        0x0000000105017448 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 631516
10  chromedriver                        0x0000000104fcce50 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326884
11  chromedriver                        0x0000000105489248 cxxbridge1$str$ptr + 2920364
12  chromedriver                        0x000000010548ca28 cxxbridge1$str$ptr + 2934668
13  chromedriver                        0x000000010546f1fc cxxbridge1$str$ptr + 2813792
14  chromedriver                        0x000000010548d2a8 cxxbridge1$str$ptr + 2936844
15  chromedriver                        0x0000000105460024 cxxbridge1$str$ptr + 2751880
16  chromedriver                        0x00000001054b2988 cxxbridge1$str$ptr + 3090156
17  chromedriver                        0x00000001054b2b04 cxxbridge1$str$ptr + 3090536
18  chromedriver                        0x00000001054c36e4 cxxbridge1$str$ptr + 3159112
19  libsystem_pthread.dylib             0x0000000185a9fc08 _pthread_start + 136
20  libsystem_pthread.dylib             0x0000000185a9aba8 thread_start + 8

      ✅ Clic OK (js) — tentative 2/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (300 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (310 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (320 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (330 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (340 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (350 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (360 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (370 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (380 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (390 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (400 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (410 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (420 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (430 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (440 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (450 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (460 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 48  (470 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 49  (480 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 50  (490 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (500 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 52  (510 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (520 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (530 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 55  (540 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (550 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (560 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (568 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 59  (578 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   ⚠️  Contenu inchangé après 30s (tentative 3/3)
   ❌ Échec après 3 tentatives.
   ✅ Dernière page atteinte.

✅ 586 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_Casablanca_Sidi_Maarouf.csv  (586 avis)

🔍 Aperçu :
  reviewer_name nationality rating            trip_type                     publication_date   stay_date language
0          Sara       Maroc    9.0  Voyageur individuel  Commentaire envoyé le 20 avril 2026  avril 2026   french
1       Nonouch       Maroc    8.0  Voyageur individuel  Commentaire envoyé le 17 avril 2026  avril 2026   french
2         Laila       Maroc    7.0  Voyageur individuel  Commentaire envoyé le 17 avril 2026  avril 2026   french
3         Tarik      France    9.0  Voyageur individuel  Commentaire envoyé le 16 avril 2026  avril 2026   french
4        Brahim       Maroc    7.0               Couple  Commentaire envoyé le 13 avril 2026   mars 2026   french
5       Zakaria       Maroc    9.0              Famille  Commentaire envoyé le 13 avril 2026  avril 2026   french
6         Majda       Maroc    8.0               Couple  Commentaire envoyé le 11 avril 2026  avril 2026   french
7        Lahcen      France    8.0  Voyageur individuel   Commentaire envoyé le 2 avril 2026  avril 2026   french
8       Mouncef       Maroc    8.0  Voyageur individuel   Commentaire envoyé le 19 mars 2026   mars 2026   french
9          Omar       Maroc    8.0              Famille   Commentaire envoyé le 15 mars 2026   mars 2026   french

📊 Colonnes vides :
  Aucune colonne vide 🎉

In [4]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-abdelmoumen.html?auth_success=1#tab-reviews"
HOTEL_NAME = "Ibis Casablanca Abdelmoumen"
HOTEL_CITY = "Casablanca"
MAX_PAGES = 300
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Casablanca Abdelmoumen (Casablanca)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (39 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (49 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (59 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (69 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (79 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (89 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (99 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (109 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (119 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (129 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (139 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (149 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (158 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (168 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (178 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (188 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (198 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (208 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (218 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (228 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (238 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (248 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (258 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (268 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (278 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (288 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (298 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (308 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (318 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (328 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (338 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (348 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (358 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (368 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (378 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (388 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (398 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (408 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (418 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (428 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (438 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (448 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (458 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (468 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (478 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (488 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (498 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (508 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (518 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (528 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (538 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (548 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (558 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (568 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (578 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (588 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (598 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (608 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (618 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (628 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (638 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (648 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (658 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (668 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (678 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (688 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (698 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (708 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (718 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (728 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (738 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (748 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (758 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (768 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (778 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (788 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (798 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (808 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (818 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (828 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (838 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (848 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (858 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (868 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (878 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (888 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (898 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (908 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (918 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (928 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (938 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (948 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (958 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (968 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (978 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (988 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (998 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1008 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1018 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1028 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1038 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1048 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1058 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1068 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1078 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1088 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1098 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1108 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1118 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1128 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1138 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1148 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 117  (1158 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 118  (1168 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 119  (1178 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1188 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1198 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1207 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 123  (1216 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 124  (1226 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1236 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 126  (1246 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 127  (1256 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 128  (1266 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 129  (1275 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 130  (1285 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 131  (1295 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 132  (1305 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 133  (1315 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 134  (1325 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 135  (1335 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'

In [5]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-casa-voyageurs.html?auth_success=1#tab-reviews"
HOTEL_NAME = "Ibis Casablanca Voyageurs"
HOTEL_CITY = "Casablanca"
MAX_PAGES = 300
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Casablanca Voyageurs (Casablanca)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (299 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (309 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (319 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (329 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (339 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (349 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (358 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (368 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (378 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (388 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (398 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (408 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (418 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (428 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (438 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (448 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (458 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (468 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (478 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (488 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (498 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (508 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (518 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (528 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (538 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (548 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (558 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (568 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (578 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (587 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (597 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (607 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (617 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (627 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (637 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (647 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (657 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (667 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (677 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (687 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (697 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (707 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (717 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (727 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (737 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (747 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (757 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (767 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (777 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (787 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (797 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (807 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (817 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (827 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (837 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (847 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (857 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (867 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (877 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (887 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (897 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (907 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (917 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (927 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (937 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (947 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (957 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (967 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (977 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (987 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (997 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1007 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1017 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1027 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1037 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1047 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1057 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1067 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1077 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1087 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1097 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1107 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1117 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1127 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1137 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1147 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1157 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 118  (1167 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1177 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1187 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1197 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1207 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 123  (1217 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 124  (1227 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1237 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 126  (1247 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 127  (1257 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 128  (1267 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 129  (1277 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 130  (1287 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 131  (1297 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 132  (1307 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 133  (1317 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 134  (1327 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 135  (1337 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 136  (1347 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 137  (1357 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 138  (1367 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 139  (1377 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 140  (1387 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 141  (1397 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 142  (1407 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 143  (1417 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3

In [6]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-casanearshore.html?aid=356980&label=gog235jc-10CAsojAFCJWliaXMtbW91c3NhZmlyLWNhc2FibGFuY2EtY2l0eS1jZW50ZXJIM1gDaIwBiAEBmAEzuAEHyAEM2AED6AEB-AEBiAIBqAIBuAKGhJ7PBsACAdICJGFlMzZiYjZmLWI3N2YtNGI1Zi1hMjljLWQ0MGIyMTg2NGIwNtgCAeACAQ&sid=53812c21f587e9070627ab5a462ac31d&dest_id=-28159&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=13&hpos=13&nflt=ht_id%3D204%3Bclass%3D3&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1776785749&srpvid=9a3a6d8a9fed049f&type=total&ucfs=1&#tab-reviews"
HOTEL_NAME = "Ibis Casablanca Nearshore"
HOTEL_CITY = "Casablanca"
MAX_PAGES = 120
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Casablanca Nearshore (Casablanca)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (300 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (310 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (320 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (329 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (339 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (349 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (359 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (369 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (379 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (389 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (399 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (409 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (419 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (429 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (439 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (449 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (459 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (469 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (479 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (489 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (499 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (509 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (519 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (529 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (539 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (549 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 57  (559 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (569 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 59  (579 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 60  (589 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (599 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (609 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (619 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (628 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 65  (636 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (646 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (656 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   ⚠️  Contenu inchangé après 30s (tentative 3/3)
   ❌ Échec après 3 tentatives.
   ✅ Dernière page atteinte.

✅ 664 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_Casablanca_Nearshore.csv  (664 avis)

🔍 Aperçu :
  reviewer_name nationality rating            trip_type                      publication_date     stay_date language
0       Mohamet      France    8.0               Couple   Commentaire envoyé le 22 avril 2026     mars 2026   french
1          Omar       Maroc    9.0  Voyageur individuel   Commentaire envoyé le 14 avril 2026    avril 2026   french
2      Boubaker       Maroc    8.0              Famille    Commentaire envoyé le 8 avril 2026    avril 2026   french
3      Boubaker       Maroc    9.0              Famille    Commentaire envoyé le 8 avril 2026    avril 2026   french
4         Ramzy     Espagne    7.0              Famille    Commentaire envoyé le 7 avril 2026    avril 2026   french
5       Mohamed       Maroc    9.0              Famille    Commentaire envoyé le 5 avril 2026    avril 2026   french
6       Yassine       Maroc    8.0              Famille  Commentaire envoyé le 1er avril 2026     mars 2026   french
7         Tarik      France    9.0  Voyageur individuel    Commentaire envoyé le 30 mars 2026  février 2026   french
8       Mohamed       Maroc    9.0  Voyageur individuel    Commentaire envoyé le 30 mars 2026     mars 2026   french
9     Christine      France    8.0              Famille    Commentaire envoyé le 30 mars 2026     mars 2026   french

📊 Colonnes vides :
  Aucune colonne vide 🎉

In [7]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-fes.fr.html?auth_success=1#tab-reviews"
HOTEL_NAME = "Ibis Moussafir Fès"
HOTEL_CITY = "Fès"
MAX_PAGES = 260
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Moussafir Fès (Fès)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (89 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (99 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (109 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (119 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (129 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (139 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (149 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (159 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (169 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (179 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (189 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (199 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (209 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (219 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (229 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (239 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (249 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (259 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (269 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (279 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (289 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (299 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (309 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (319 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (328 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (338 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (348 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (358 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (368 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (378 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (388 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (398 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (408 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (418 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (428 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (438 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (448 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (458 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (468 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (478 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (488 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (498 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (508 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (517 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (527 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (537 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (547 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (557 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (567 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (577 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (587 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (597 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (607 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (617 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (627 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (637 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (647 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (657 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (667 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (677 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (687 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (697 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (707 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (717 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (727 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (737 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (747 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (757 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (767 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (777 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (787 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (797 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (807 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (817 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (827 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (837 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (847 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (857 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (867 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (877 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (887 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (897 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (907 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (917 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (927 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (937 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (947 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (957 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (967 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (977 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (986 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (996 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1006 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1016 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1026 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1036 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1046 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1056 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1066 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1076 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1086 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1096 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1106 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1116 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1126 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1136 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1146 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1156 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 118  (1166 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1176 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1186 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1196 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1206 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 123  (1216 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 124  (1226 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1236 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 126  (1246 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 127  (1256 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 128  (1266 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 129  (1276 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 130  (1286 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 131  (1296 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 132  (1306 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 133  (1316 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 134  (1326 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 135  (1336 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 136  (1346 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 137  (1356 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 138  (1366 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 139  (1376 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 140  (1386 avis cumulés)
      → 10 nouveaux avis

In [8]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-rabat-agdal.html?aid=356980&label=gog235jc-10CAsojAFCEGliaXMtcmFiYXQtYWdkYWxIM1gDaIwBiAEBmAEzuAEHyAEM2AED6AEB-AEBiAIBqAIBuALV2aPPBsACAdICJDg3YzJkNWJhLTQwYjQtNDhjMi1hM2YyLTg5YTdiNWJiMzJhONgCAeACAQ&sid=53812c21f587e9070627ab5a462ac31d&dest_id=-43376&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1776872670&srpvid=a1986eaba28a035f&type=total&ucfs=1&#tab-reviews"
HOTEL_NAME = "Ibis Rabat Agdal"
HOTEL_CITY = "Rabat"
MAX_PAGES = 200
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Rabat Agdal (Rabat)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (269 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (279 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (289 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (299 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (309 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (319 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (329 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (339 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (349 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (359 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (369 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (379 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (389 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (399 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (409 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (419 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (429 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (439 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (449 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (459 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (469 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (479 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (489 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (499 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (509 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (519 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (529 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (539 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (549 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (559 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (569 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (579 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (589 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (599 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (609 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (619 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (629 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (639 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (649 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (659 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (669 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (679 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (689 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (699 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (709 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 73  (719 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (729 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (739 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (749 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (759 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (769 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (779 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (789 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (799 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (809 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (819 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (829 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (839 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (849 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (859 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (869 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (879 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (889 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (899 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (909 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (919 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (929 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (939 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (949 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (959 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (969 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (979 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (989 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (999 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1009 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1018 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1028 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 105  (1037 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 106  (1047 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1056 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 108  (1066 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1076 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1086 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1096 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1106 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1116 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1126 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1136 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1145 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1155 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 118  (1165 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1175 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1185 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1195 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1204 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 123  (1214 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 124  (1223 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1231 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 126  (1241 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 127  (1251 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   ⚠️  Contenu inchangé après 30s (tentative 3/3)
   ❌ Échec après 3 tentatives.
   ✅ Dernière page atteinte.

✅ 1261 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_Rabat_Agdal.csv  (1261 avis)

🔍 Aperçu :
  reviewer_name    nationality rating            trip_type                     publication_date     stay_date language
0        Khalid          Maroc    9.0              Famille  Commentaire envoyé le 14 avril 2026    avril 2026   french
1       Yacouba  Côte-d'Ivoire    7.0  Voyageur individuel  Commentaire envoyé le 11 avril 2026    avril 2026   french

In [6]:
df.head()

,source,hotel_name,hotel_city,reviewer_name,nationality,rating,review_title,review_text,positive_comment,negative_comment,publication_date,stay_date,trip_type,language
0,booking.com,Ibis Moussafir Fès,Fès,Marianne,Canada,6.0,"Séjour correcte, nous recommandons lors de tem...",L’emplacement et la terrasse Aucune climatisat...,L’emplacement et la terrasse,Aucune climatisation (froid) dans les chambres...,Commentaire envoyé le 20 avril 2026,avril 2026,Couple,french
1,booking.com,Ibis Moussafir Fès,Fès,Nezha,France,7.0,agreable,le personnel de la restauration au top très pr...,le personnel de la restauration au top très pr...,petit déjeuner pas assez varier .on aurait aim...,Commentaire envoyé le 20 avril 2026,mars 2026,Couple,french
2,booking.com,Ibis Moussafir Fès,Fès,Mesoudi,Maroc,6.0,Séjour a ibis fes,J'ai aimer l'emplacement et les gens d'acceuil...,J'ai aimer l'emplacement et les gens d'acceuil,Il faut changer les serviettes de la salle de ...,Commentaire envoyé le 19 avril 2026,avril 2026,Voyageur individuel,french
3,booking.com,Ibis Moussafir Fès,Fès,Sophie,Suisse,7.0,Bien,Jardin Bruit du train et rue côté gare,Jardin,Bruit du train et rue côté gare,Commentaire envoyé le 17 avril 2026,avril 2026,Voyageur individuel,french
4,booking.com,Ibis Moussafir Fès,Fès,Taoufiq,France,7.0,Quelques inconvénients bruit dans le couloir,Bien situé Odeur de la cigarette dans la chambre,Bien situé,Odeur de la cigarette dans la chambre,Commentaire envoyé le 13 avril 2026,avril 2026,Couple,french

In [9]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-tanger-city-center.html?aid=356980&label=gog235jc-10CAsojAFCIWliaXMtbW91c3NhZmlyLXRhbmdlci1jaXR5LWNlbnRlckgzWANojAGIAQGYATO4AQfIAQ3YAQPoAQH4AQGIAgGoAgG4AsDgo88GwAIB0gIkZTJjYmZmYzQtZWVlOC00MTQ2LWI5MjYtYzEyMzViMDI1OTMy2AIB4AIB&sid=4ba5cffa630e66002a1045ea6b678064&dist=0&keep_landing=1&sb_price_type=total&type=total&lang=en-us&soz=1&lang_changed=1#tab-reviews"
HOTEL_NAME = "Ibis Tanger City Center"
HOTEL_CITY = "Tanger"
MAX_PAGES = 300
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Tanger City Center (Tanger)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (300 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (310 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (320 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (330 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (340 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (350 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (360 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (370 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (380 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (390 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (400 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (410 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (420 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (430 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (440 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (450 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (459 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (469 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (479 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (489 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (499 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (509 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (519 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (529 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (539 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (549 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (559 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (569 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (579 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (589 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (599 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (609 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (619 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (629 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (639 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (649 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (659 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (669 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (679 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (689 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (699 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (709 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (719 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (729 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (739 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (749 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (759 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (769 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (779 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (789 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (799 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (809 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (819 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (829 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (839 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (849 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (859 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (869 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (879 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (889 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (899 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (909 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (919 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (929 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (939 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (949 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (959 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (969 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (979 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (989 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (999 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1007 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1017 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1027 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1037 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1047 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1057 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1067 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1077 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1087 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1097 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1107 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1117 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1127 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1137 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1147 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1157 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 118  (1167 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1177 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1187 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1197 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1207 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 123  (1217 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 124  (1227 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1237 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 126  (1247 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 127  (1257 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 128  (1267 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 129  (1277 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 130  (1287 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 131  (1297 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 132  (1307 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 133  (1317 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 134  (1327 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 135  (1337 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 136  (1347 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 137  (1357 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 138  (1367 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 139  (1377 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 140  (1387 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 141  (1397 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 142  (1407 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 143  (1417 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 144  (1427 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 145  (1437 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 146  (1447 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 147  (1457 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 148  (1467 avis cumulés)

In [10]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-marrakech-centre-gare.html?aid=356980&label=gog235jc-10CAsojAFCJGliaXMtbW91c3NhZmlyLW1hcnJha2VjaC1jZW50cmUtZ2FyZUgNWANojAGIAQGYATO4AQfIAQ3YAQPoAQH4AQGIAgGoAgG4Atnmo88GwAIB0gIkZmQwYjBjNDAtMTAxNC00MzQ0LTlhZDAtMjU1OThlYjAyNGUx2AIB4AIB&sid=4ba5cffa630e66002a1045ea6b678064&dist=0&keep_landing=1&sb_price_type=total&type=total&#tab-reviews"
HOTEL_NAME = "Ibis Marrakech Centre Gare"
HOTEL_CITY = "Marrakech"
MAX_PAGES = 250
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Marrakech Centre Gare (Marrakech)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (300 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (310 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (320 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (330 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (340 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (350 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (360 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (370 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (380 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (390 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (400 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (410 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (420 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (430 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (440 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (450 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (460 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (470 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (480 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (490 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (500 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (510 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (520 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (530 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (540 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (550 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (560 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (570 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (580 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (590 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (600 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (610 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (620 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (630 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (640 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (650 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (660 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (670 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (680 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (690 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (700 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (710 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (720 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (730 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (740 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (750 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (760 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (770 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (780 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (790 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (800 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (810 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (820 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (830 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (840 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (850 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (860 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (870 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (880 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (890 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (900 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (910 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (920 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (930 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (940 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (950 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (960 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (970 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (980 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (990 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (1000 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1010 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1020 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1030 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1040 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1049 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1059 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1069 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1079 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1089 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1099 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1109 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1119 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1129 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1139 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1149 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1159 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 118  (1168 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1178 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1188 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1198 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1208 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 123  (1218 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 124  (1228 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1238 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 126  (1248 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 127  (1258 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 128  (1268 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 129  (1278 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 130  (1288 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 131  (1298 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 132  (1308 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 133  (1318 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 134  (1328 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 135  (1338 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 136  (1348 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 137  (1358 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 138  (1368 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 139  (1378 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 140  (1388 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 141  (1398 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 142  (1408 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'

In [11]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-marrakech-palmeraie.html?aid=356980&label=gog235jc-10CAsojAFCImliaXMtbW91c3NhZmlyLW1hcnJha2VjaC1wYWxtZXJhaWVIDVgDaIwBiAEBmAEzuAEHyAEN2AED6AEB-AEBiAIBqAIBuAKC7aPPBsACAdICJDYwZDZmYTk5LTIxZjUtNDQ1Ni1hNGE5LWFjYTFjMDc0ZjRjYdgCAeACAQ&sid=4ba5cffa630e66002a1045ea6b678064&dist=0&keep_landing=1&sb_price_type=total&type=total&#tab-reviews"
HOTEL_NAME = "Ibis Marrakech Palmeraie"
HOTEL_CITY = "Marrakech"
MAX_PAGES = 200
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Marrakech Palmeraie (Marrakech)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (78 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (88 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (98 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (108 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (118 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (128 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (138 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (148 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (158 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (168 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (178 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (188 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (198 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (208 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (218 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (228 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (238 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (248 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 27  (258 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (268 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (278 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (288 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (298 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (308 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (318 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (328 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (338 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (348 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (358 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (368 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (378 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (388 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (398 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (408 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (418 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (428 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (438 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (448 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (458 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (468 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (478 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (488 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (498 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (508 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (518 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (528 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (538 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (548 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (558 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (568 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (578 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (588 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (598 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (608 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 63  (618 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (628 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (638 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (648 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (658 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (668 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (678 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (688 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (698 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (708 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (718 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (728 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (738 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (748 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (758 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (768 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 79  (778 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (788 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (798 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (808 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (818 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (828 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (838 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (848 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (858 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (868 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (878 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (888 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (898 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (908 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (918 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (928 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (938 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (948 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (958 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (968 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (978 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (988 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (998 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 102  (1008 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 103  (1018 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1028 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1038 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1048 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1058 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1067 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1077 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1087 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1097 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1107 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1116 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1126 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1136 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1145 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1155 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 118  (1165 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1174 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1184 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1194 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 122  (1204 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 123  (1214 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 124  (1224 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 125  (1234 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 126  (1244 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 127  (1254 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 128  (1264 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 129  (1274 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'

In [13]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-meknes.html?aid=356980&label=gog235jc-10CAsojAFCFWliaXMtbW91c3NhZmlyLW1la25lc0gNWANojAGIAQGYATO4AQfIAQzYAQPoAQH4AQGIAgGoAgG4AuWApM8GwAIB0gIkZDBjODQ3NmEtNDAwYS00OTZkLTgyZDItNDlmMDU5YTU2ZjA42AIB4AIB&sid=53812c21f587e9070627ab5a462ac31d&dest_id=-39119&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1776877683&srpvid=4f43787355a2074e&type=total&ucfs=1&lang=en-us&soz=1&lang_changed=1#tab-reviews"
HOTEL_NAME = "Ibis Meknes"
HOTEL_CITY = "Meknes"
MAX_PAGES = 120
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Meknes (Meknes)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (39 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (49 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (59 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (69 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (79 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (89 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (99 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (109 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (119 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (129 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (139 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (149 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (159 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (169 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (179 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (189 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (199 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (209 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (219 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (229 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (239 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (249 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (259 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (269 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (279 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (289 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (299 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (309 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (319 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (329 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (339 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (349 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (359 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (369 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (379 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (389 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (399 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (409 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (419 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (429 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (439 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (449 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (459 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (469 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (479 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (489 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (498 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (508 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (518 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (528 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (538 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (548 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (558 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (568 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (578 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (588 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (598 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (608 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (618 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (628 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (638 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (648 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (657 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (667 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (677 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (687 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (696 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 72  (706 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 73  (716 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (726 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 75  (736 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (744 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 77  (754 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 78  (764 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 79  (773 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next page'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Next'
      ⚠️  Clic normal échoué : Message: element not interactable
  (Session info: chrome=147.0.7727.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementnotinteractableexception
Stacktrace:
0   chromedriver                        0x0000000102617abc cxxbridge1$str$ptr + 3192864
1   chromedriver                        0x000000010260fa8c cxxbridge1$str$ptr + 3160048
2   chromedriver                        0x00000001020db5c4 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 74840
3   chromedriver                        0x00000001021244b0 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 373572
4   chromedriver                        0x000000010211a8dc _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 333680
5   chromedriver                        0x000000010211a358 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 332268
6   chromedriver                        0x0000000102163448 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 631516
7   chromedriver                        0x0000000102118e50 _RNvCs10ygTOo3JCa_7___rustc35___rust_no_alloc_shim_is_unstable_v2 + 326884
8   chromedriver                        0x00000001025d5248 cxxbridge1$str$ptr + 2920364
9   chromedriver                        0x00000001025d8a28 cxxbridge1$str$ptr + 2934668
10  chromedriver                        0x00000001025bb1fc cxxbridge1$str$ptr + 2813792
11  chromedriver                        0x00000001025d92a8 cxxbridge1$str$ptr + 2936844
12  chromedriver                        0x00000001025ac024 cxxbridge1$str$ptr + 2751880
13  chromedriver                        0x00000001025fe988 cxxbridge1$str$ptr + 3090156
14  chromedriver                        0x00000001025feb04 cxxbridge1$str$ptr + 3090536
15  chromedriver                        0x000000010260f6e4 cxxbridge1$str$ptr + 3159112
16  libsystem_pthread.dylib             0x0000000185a9fc08 _pthread_start + 136
17  libsystem_pthread.dylib             0x0000000185a9aba8 thread_start + 8

      ✅ Clic OK (js) — tentative 3/3
   ⚠️  Contenu inchangé après 30s (tentative 3/3)
   ❌ Échec après 3 tentatives.
   ✅ Dernière page atteinte.

✅ 783 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_Meknes.csv  (783 avis)

🔍 Aperçu :
  reviewer_name     nationality rating      trip_type    publication_date       stay_date language
0      Cristina        Portugal    7.0         Couple      March 22, 2026      March 2026  english
1         Rabie          Greece    7.0         Couple     October 9, 2025  September 2025  english
2        Jacqui  United Kingdom    7.0         Family  September 29, 2025  September 2025  english
3        Safian  United Kingdom    7.0  Solo traveler  September 19, 2025  September 2025  english
4         Ahmed           Egypt    7.0  Solo traveler  September 12, 2025  September 2025  english
5         Naeer         Morocco    7.0         Family       July 14, 2025       July 2025  english
6         Bryan        Portugal    8.0          Group        May 14, 2025        May 2025  english
7       Jessica       Gibraltar    7.0         Couple         May 9, 2025        May 2025  english
8        Claire  United Kingdom    6.0         Family      April 18, 2025      April 2025  english
9        Fatima  United Kingdom    8.0         Family      April 18, 2025      April 2025  english

📊 Colonnes vides :
  Aucune colonne vide 🎉

In [15]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-oujda.html?aid=356980&label=gog235jc-10CAsojAFCFWliaXMtbW91c3NhZmlyLW1la25lc0gNWANojAGIAQGYATO4AQfIAQzYAQPoAQH4AQGIAgGoAgG4AuWApM8GwAIB0gIkZDBjODQ3NmEtNDAwYS00OTZkLTgyZDItNDlmMDU5YTU2ZjA42AIB4AIB&sid=53812c21f587e9070627ab5a462ac31d&dest_id=98912&dest_type=hotel&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1776879998&srpvid=8c427cf522e50d6e&type=total&ucfs=1&#tab-reviews"
HOTEL_NAME = "Ibis Oujda"
HOTEL_CITY = "Oujda"
MAX_PAGES = 80
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Oujda (Oujda)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (300 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (310 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 33  (320 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (330 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (340 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (350 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (359 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (369 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (379 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 40  (389 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (399 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (409 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 43  (419 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (428 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (438 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (448 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (458 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (468 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (478 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (488 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (498 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 52  (508 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (518 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (528 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (538 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (548 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (558 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (568 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (577 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 60  (587 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (597 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (607 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (617 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (626 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
   ✅ Bouton désactivé — dernière page atteinte.
   ✅ Dernière page atteinte.

✅ 636 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_Oujda.csv  (636 avis)

🔍 Aperçu :
  reviewer_name nationality rating            trip_type                       publication_date     stay_date language
0       Arrahal       Maroc    7.0               Couple    Commentaire envoyé le 18 avril 2026    avril 2026   french
1       Taoussi       Maroc    8.0               Couple     Commentaire envoyé le 9 avril 2026    avril 2026   french
2       Lamjadi      France    7.0              Famille     Commentaire envoyé le 4 avril 2026    avril 2026   french
3         Radia      France    6.0               Couple     Commentaire envoyé le 2 avril 2026    avril 2026   french
4       Rahmona      France    8.0               Couple     Commentaire envoyé le 26 mars 2026     mars 2026   french
5        Fatiha    Belgique    8.0               Couple     Commentaire envoyé le 16 mars 2026     mars 2026   french
6        Hanane      France    7.0  Voyageur individuel  Commentaire envoyé le 18 février 2026  février 2026   french
7        Ouarga       Maroc    7.0  Voyageur individuel  Commentaire envoyé le 19 janvier 2026  janvier 2026  unknown
8       Jeffali      France    8.0              Famille  Commentaire envoyé le 16 janvier 2026  janvier 2026   french
9        Brahim       Maroc    7.0  Voyageur individuel  Commentaire envoyé le 16 janvier 2026  janvier 2026   french

📊 Colonnes vides :
nationality    2
dtype: int64

In [16]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-mohammedia.html?aid=356980&label=gog235jc-10CAsojAFCD2liaXMtbW9oYW1tZWRpYUgNWANojAGIAQGYATO4AQfIAQ3YAQPoAQH4AQGIAgGoAgG4Ao2mpM8GwAIB0gIkOTNjZjE4YmEtMGYzYS00NzQ1LWE1ODgtNDJkZDE4NWVmODM32AIB4AIB&sid=4ba5cffa630e66002a1045ea6b678064&dist=0&keep_landing=1&sb_price_type=total&type=total&#tab-reviews"
HOTEL_NAME = "Ibis Mohammedia"
HOTEL_CITY = "Mohammedia"
MAX_PAGES = 120
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Mohammedia (Mohammedia)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (19 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (29 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (39 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (49 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (59 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (69 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (79 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (89 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (99 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (109 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (119 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (129 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (139 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (149 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (159 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (169 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (179 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (189 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (199 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (209 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (219 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (229 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (239 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (249 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (259 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (269 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (279 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (289 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (299 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (309 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (319 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (329 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (339 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (349 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (359 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (369 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (379 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (389 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (399 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (409 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (419 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (429 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (439 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (449 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (459 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (469 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (479 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (489 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (499 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (509 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (519 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (529 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (539 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (548 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (558 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 58  (567 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (577 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 60  (587 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (597 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 62  (606 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 63  (615 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (624 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (633 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 66  (643 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (653 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (662 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (671 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (681 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (691 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (701 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (711 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (721 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (731 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (741 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 77  (751 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (761 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (770 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (780 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (790 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (800 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 83  (810 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (820 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (830 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 86  (840 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (850 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (860 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (870 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (880 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (890 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (898 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (908 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 94  (918 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 95  (928 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (938 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (948 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (958 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (968 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (978 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (988 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 102  (998 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1008 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 104  (1018 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 105  (1028 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1038 avis cumulés)
      → 7 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1045 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 108  (1054 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 109  (1064 avis cumulés)
      → 3 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
   ✅ Bouton désactivé — dernière page atteinte.
   ✅ Dernière page atteinte.

✅ 1067 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_Mohammedia.csv  (1067 avis)

🔍 Aperçu :
  reviewer_name nationality rating            trip_type                       publication_date     stay_date language
0          René      France    8.0               Couple    Commentaire envoyé le 14 avril 2026    avril 2026   french
1          Amal     Espagne    7.0               Couple    Commentaire envoyé le 11 avril 2026    avril 2026   french
2     Magdaléna      France    7.0               Couple     Commentaire envoyé le 7 avril 2026     mars 2026   french
3         Driss       Maroc    8.0  Voyageur individuel     Commentaire envoyé le 6 avril 2026    avril 2026   french
4       Hannane       Maroc    7.0  Voyageur individuel     Commentaire envoyé le 31 mars 2026     mars 2026   french
5        Sylman      France    6.0               Couple     Commentaire envoyé le 30 mars 2026     mars 2026   french
6        Bentat       Maroc    8.0  Voyageur individuel  Commentaire envoyé le 17 février 2026  février 2026   french
7       Belkhir      France    7.0               Couple   Commentaire envoyé le 2 février 2026  janvier 2026   french
8       Laurent      France    7.0               Groupe  Commentaire envoyé le 30 janvier 2026  janvier 2026   french
9       Jahjouh       Maroc    8.0              Famille  Commentaire envoyé le 27 janvier 2026  janvier 2026   french

📊 Colonnes vides :
nationality    3
dtype: int64

In [17]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-ouarzazate.html?aid=356980&label=gog235jc-10CAsojAFCGWliaXMtbW91c3NhZmlyLW91YXJ6YXphdGVIDVgDaIwBiAEBmAEzuAEHyAEN2AED6AEB-AEBiAIBqAIBuAKBxKTPBsACAdICJDYyMTY5NWYzLWYxODctNDg2ZS04MWVjLTk4MTg2ODY0MzU3ZdgCAeACAQ&sid=4ba5cffa630e66002a1045ea6b678064&dist=0&keep_landing=1&sb_price_type=total&type=total&#tab-reviews"
HOTEL_NAME = "Ibis Ouarzazate"
HOTEL_CITY = "Ouarzazate"
MAX_PAGES = 190
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis Ouarzazate (Ouarzazate)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (300 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (310 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (320 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (330 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (340 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (350 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (360 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (370 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (380 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (390 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (400 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (410 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (420 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (430 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (440 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (450 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 47  (460 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (470 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 49  (480 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (490 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 51  (500 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 52  (510 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 53  (520 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 54  (530 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 55  (540 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 56  (550 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 57  (560 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 58  (570 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 59  (580 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 60  (590 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 61  (600 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 62  (610 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 63  (620 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 64  (630 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 65  (640 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 66  (650 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 67  (660 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 68  (670 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 69  (680 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 70  (690 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 71  (700 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 72  (710 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 73  (720 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 74  (730 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 75  (740 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 76  (750 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 77  (760 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 78  (770 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 79  (780 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 80  (790 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 81  (800 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 82  (810 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 83  (820 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 84  (830 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 85  (840 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 86  (850 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 87  (860 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 88  (870 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 89  (880 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 90  (890 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 91  (900 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 92  (910 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 93  (920 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 94  (930 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 95  (940 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 96  (950 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 97  (960 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 98  (970 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 99  (980 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 100  (990 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 101  (1000 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 102  (1010 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 103  (1020 avis cumulés)
      → 8 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 104  (1028 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 105  (1038 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 106  (1048 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 107  (1058 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 108  (1068 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 109  (1077 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 110  (1087 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 111  (1097 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 112  (1107 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 113  (1117 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 114  (1127 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 115  (1137 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 116  (1147 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 117  (1157 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 118  (1167 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 119  (1177 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 120  (1187 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 121  (1197 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   ⚠️  Contenu inchangé après 30s (tentative 3/3)
   ❌ Échec après 3 tentatives.
   ✅ Dernière page atteinte.

✅ 1207 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_Ouarzazate.csv  (1207 avis)

🔍 Aperçu :
  reviewer_name nationality rating            trip_type                     publication_date   stay_date language
0      Cristina      France    9.0               Couple  Commentaire envoyé le 22 avril 2026  avril 2026   french
1         Manal       Maroc    8.0  Voyageur individuel  Commentaire envoyé le 20 avril 2026  avril 2026   french
2          Dgpn      Suisse    7.0  Voyageur individuel  Commentaire envoyé le 20 avril 2026  avril 2026   french
3      Zakaryae      France    8.0              Famille  Commentaire envoyé le 17 avril 2026  avril 2026   french
4        Franck      France    8.0  Voyageur individuel  Commentaire envoyé le 17 avril 2026  avril 2026   french
5        Pierre      France    7.0               Groupe  Commentaire envoyé le 16 avril 2026  avril 2026   french
6        Jérôme      Suisse    8.0  Voyageur individuel  Commentaire envoyé le 11 avril 2026  avril 2026   french
7        Pascal      France    8.0  Voyageur individuel  Commentaire envoyé le 11 avril 2026  avril 2026   french
8         Sonia      France    9.0               Couple  Commentaire envoyé le 10 avril 2026  avril 2026   french
9  Page-lecuyer      France    7.0               Groupe   Commentaire envoyé le 5 avril 2026  avril 2026   french

📊 Colonnes vides :
nationality    2
dtype: int64

In [18]:
import time
import re
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from lingua import Language, LanguageDetectorBuilder

# ==================================================
URL = "https://www.booking.com/hotel/ma/ibis-moussafir-el-jadida.html?aid=356980&label=gog235jc-10CAsojAFCGGliaXMtbW91c3NhZmlyLWVsLWphZGlkYUgNWANojAGIAQGYATO4AQfIAQ3YAQPoAQH4AQGIAgGoAgG4As3KpM8GwAIB0gIkZjI4MDVkM2UtMjI4Yi00OWE2LTlhMzItYzc4ZGQyMWZlODY52AIB4AIB&sid=4ba5cffa630e66002a1045ea6b678064&dist=0&keep_landing=1&sb_price_type=total&type=total&#tab-reviews"
HOTEL_NAME = "Ibis El Jadida"
HOTEL_CITY = "El Jadida"
MAX_PAGES = 90
# ==================================================


class BookingScraper:
    def __init__(self):
        options = Options()
        options.add_argument('--lang=en')
        options.add_argument('--disable-blink-features=AutomationControlled')
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option('useAutomationExtension', False)
        options.add_argument(
            '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) '
            'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
        )
        self.driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=options
        )
        self.wait = WebDriverWait(self.driver, 20)

        self.detector = LanguageDetectorBuilder.from_languages(
            Language.FRENCH, Language.ENGLISH, Language.GERMAN,
            Language.SPANISH, Language.ITALIAN, Language.PORTUGUESE,
            Language.DUTCH, Language.RUSSIAN, Language.ARABIC, Language.CHINESE,
        ).with_minimum_relative_distance(0.15).build()

        self._lang_map = {
            Language.FRENCH: "french", Language.ENGLISH: "english",
            Language.GERMAN: "german", Language.SPANISH: "spanish",
            Language.ITALIAN: "italian", Language.PORTUGUESE: "portuguese",
            Language.DUTCH: "dutch", Language.RUSSIAN: "russian",
            Language.ARABIC: "arabic", Language.CHINESE: "chinese",
        }

    def _text(self, parent, css):
        try:
            return parent.find_element(By.CSS_SELECTOR, css).text.strip()
        except Exception:
            return ""

    def _first_text(self, parent, *selectors):
        for sel in selectors:
            val = self._text(parent, sel)
            if val:
                return val
        return ""

    def _extract_number(self, raw):
        if not raw:
            return ""
        raw = raw.replace(",", ".")
        match = re.search(r'\d+(?:\.\d+)?', raw)
        return match.group(0) if match else ""

    def detect_language(self, text):
        if not text or len(text.strip()) < 5:
            return "unknown"
        try:
            lang = self.detector.detect_language_of(text)
            return self._lang_map.get(lang, "unknown") if lang else "unknown"
        except Exception:
            return "unknown"

    def _get_snapshot(self):
        try:
            card = self.driver.find_element(By.CSS_SELECTOR, "div[data-testid='review-card']")
            for sel in [
                "div[data-testid='review-positive-text']",
                "div[data-testid='review-negative-text']",
                "h4[data-testid='review-title']",
            ]:
                try:
                    t = card.find_element(By.CSS_SELECTOR, sel).text.strip()
                    if t:
                        return t
                except Exception:
                    pass
        except Exception:
            pass
        return ""

    def _next_page(self, snapshot_before):
        MAX_RETRIES = 3

        for attempt in range(1, MAX_RETRIES + 1):
            btn = None

            labels = ["Page suivante", "Suivant", "Next page", "Next"]
            for label in labels:
                try:
                    btn = self.driver.find_element(
                        By.CSS_SELECTOR, f"button[aria-label='{label}']"
                    )
                    print(f"      🔘 Bouton trouvé : '{label}'")
                    break
                except Exception:
                    pass

            if btn is None:
                try:
                    btn = self.driver.find_element(
                        By.XPATH,
                        "//button[contains(@aria-label,'suivante') or "
                        "contains(@aria-label,'Suivant') or "
                        "contains(@aria-label,'Next')]"
                    )
                    print(f"      🔘 Bouton via XPath : '{btn.get_attribute('aria-label')}'")
                except Exception:
                    pass

            if btn is None:
                print("   ⚠️  Bouton introuvable.")
                return False

            disabled      = btn.get_attribute("disabled")
            aria_disabled = btn.get_attribute("aria-disabled") or ""
            classes       = btn.get_attribute("class") or ""
            if disabled or aria_disabled == "true" or "disabled" in classes:
                print("   ✅ Bouton désactivé — dernière page atteinte.")
                return False

            try:
                self.driver.execute_script(
                    "arguments[0].scrollIntoView({block:'center'});", btn
                )
                time.sleep(1)
            except Exception:
                pass

            clicked = False
            for method in ['normal', 'js']:
                try:
                    if method == 'normal':
                        btn.click()
                    else:
                        self.driver.execute_script("arguments[0].click();", btn)
                    clicked = True
                    print(f"      ✅ Clic OK ({method}) — tentative {attempt}/{MAX_RETRIES}")
                    break
                except Exception as e:
                    print(f"      ⚠️  Clic {method} échoué : {e}")

            if not clicked:
                time.sleep(2)
                continue

            for _ in range(60):
                time.sleep(0.5)
                try:
                    cards = self.driver.find_elements(
                        By.CSS_SELECTOR, "div[data-testid='review-card']"
                    )
                    if not cards:
                        continue
                    first_text = ""
                    for sel in [
                        "div[data-testid='review-positive-text']",
                        "div[data-testid='review-negative-text']",
                        "h4[data-testid='review-title']",
                    ]:
                        try:
                            t = cards[0].find_element(By.CSS_SELECTOR, sel).text.strip()
                            if t:
                                first_text = t
                                break
                        except Exception:
                            pass
                    if first_text and first_text != snapshot_before:
                        return True
                except Exception:
                    pass

            print(f"   ⚠️  Contenu inchangé après 30s (tentative {attempt}/{MAX_RETRIES})")

            if attempt < MAX_RETRIES:
                print(f"   🔄 Nouvelle tentative dans 3s...")
                self.driver.execute_script("window.scrollTo(0, 0);")
                time.sleep(3)

        print("   ❌ Échec après 3 tentatives.")
        return False

    def _parse_card(self, card, hotel_name, hotel_city):
        name = self._first_text(
            card,
            "div.b08850ce41.f546354b44",
            "div[data-testid='reviewer-name'] span",
            "p.reviewer_name",
        )
        nationality = self._first_text(
            card,
            "span.d838fb5f41.aea5eccb71",
            "span[class*='reviewer_country']",
            "div[data-testid='reviewer-country'] span",
        )
        raw_rating = self._first_text(
            card,
            "div[data-testid='review-score'] div.bc946a29db",
            "div[data-testid='review-score']",
            "div.bui-review-score__badge",
        )
        rating    = self._extract_number(raw_rating)
        title     = self._first_text(card, "h4[data-testid='review-title']", "h3[class*='title']")
        pub_date  = self._first_text(card, "span[data-testid='review-date']", "p[data-testid='review-date']")
        pub_date  = re.sub(r'^Reviewed\s*:\s*', '', pub_date).strip()
        pub_date  = re.sub(r'^Rédigé le\s*:\s*', '', pub_date).strip()
        stay_date = self._first_text(card, "span[data-testid='review-stay-date']", "p.review_staydate")
        stay_date = re.sub(r'^Stayed\s*:\s*', '', stay_date).strip()
        stay_date = re.sub(r'^Séjour\s*:\s*', '', stay_date).strip()
        trip_type = self._first_text(
            card,
            "span[data-testid='review-traveler-type']",
            "p[data-testid='travel-type']",
            "div[data-testid='review-travel-type']",
        )
        pos  = self._text(card, "div[data-testid='review-positive-text']")
        neg  = self._text(card, "div[data-testid='review-negative-text']")
        full = (pos + " " + neg).strip()

        sub_scores = {}
        try:
            subs = card.find_elements(By.CSS_SELECTOR, "div[data-testid='review-subscore']")
            for s in subs:
                try:
                    cat = s.find_element(By.CSS_SELECTOR, "span").text.strip()
                    val = s.find_element(By.CSS_SELECTOR, "div.bc946a29db").text.strip()
                    sub_scores[cat] = self._extract_number(val)
                except Exception:
                    pass
        except Exception:
            pass

        return {
            "source": "booking.com",
            "hotel_name": hotel_name,
            "hotel_city": hotel_city,
            "reviewer_name": name,
            "nationality": nationality,
            "rating": rating,
            "review_title": title,
            "review_text": full,
            "positive_comment": pos,
            "negative_comment": neg,
            "publication_date": pub_date,
            "stay_date": stay_date,
            "trip_type": trip_type,
            "language": self.detect_language(full),
            **sub_scores,
        }

    def scrape_reviews(self, url, hotel_name, hotel_city, max_pages=90):
        print(f"🔄 Scraping : {hotel_name} ({hotel_city})")
        self.driver.get(url)
        time.sleep(6)

        all_reviews = []
        seen = set()
        page = 1

        while page <= max_pages:
            print(f"   📄 Page {page}  ({len(all_reviews)} avis cumulés)")

            try:
                self.wait.until(
                    EC.presence_of_element_located(
                        (By.CSS_SELECTOR, "div[data-testid='review-card']")
                    )
                )
            except Exception:
                print("   ⚠️  Aucune carte trouvée, fin du scraping.")
                break

            cards = self.driver.find_elements(
                By.CSS_SELECTOR, "div[data-testid='review-card']"
            )
            if not cards:
                print("   ⚠️  Liste de cartes vide, fin du scraping.")
                break

            snap = self._get_snapshot()

            new_count = 0
            for card in cards:
                review = self._parse_card(card, hotel_name, hotel_city)
                key = (
                    review.get("reviewer_name", ""),
                    review.get("publication_date", ""),
                    review.get("rating", ""),
                    review.get("review_text", "")[:50],
                )
                if key not in seen:
                    seen.add(key)
                    all_reviews.append(review)
                    new_count += 1

            print(f"      → {new_count} nouveaux avis")

            if new_count == 0:
                print("   ⚠️  Aucun nouvel avis — boucle détectée, arrêt.")
                break

            if not self._next_page(snap):
                print("   ✅ Dernière page atteinte.")
                break

            page += 1

        self.driver.quit()
        print(f"\n✅ {len(all_reviews)} avis extraits au total")
        return pd.DataFrame(all_reviews)


# ==================================================
if __name__ == "__main__":
    scraper = BookingScraper()
    df = scraper.scrape_reviews(URL, HOTEL_NAME, HOTEL_CITY, max_pages=MAX_PAGES)

    if not df.empty:
        filename = f"avis_{HOTEL_NAME.replace(' ', '_')}.csv"
        df.to_csv(filename, index=False, encoding='utf-8-sig')
        print(f"\n💾 Fichier sauvegardé : {filename}  ({len(df)} avis)")

        print("\n🔍 Aperçu :")
        cols = [c for c in ["reviewer_name", "nationality", "rating",
                             "trip_type", "publication_date", "stay_date",
                             "language"] if c in df.columns]
        print(df[cols].head(10).to_string())

        print("\n📊 Colonnes vides :")
        empty = df[cols].isnull().sum() + (df[cols] == "").sum()
        print(empty[empty > 0] if empty[empty > 0].any() else "  Aucune colonne vide 🎉")
    else:
        print("❌ Aucun avis extrait.")

🔄 Scraping : Ibis El Jadida (El Jadida)
   📄 Page 1  (0 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 2  (10 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 3  (20 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 4  (30 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 5  (40 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 6  (50 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 7  (60 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 8  (70 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 9  (80 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 10  (90 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 11  (100 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 12  (110 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 13  (120 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 14  (130 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 15  (140 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 16  (150 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 17  (160 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 18  (170 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 19  (180 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 20  (190 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 21  (200 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 22  (210 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 23  (220 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 24  (230 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 25  (240 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 26  (250 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 27  (260 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 28  (270 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 29  (280 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 30  (290 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 31  (300 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 32  (310 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 33  (320 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 34  (330 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 35  (340 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 36  (350 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 37  (360 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 38  (370 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 39  (380 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 40  (390 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 41  (400 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 42  (410 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 43  (420 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 44  (430 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 45  (440 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 46  (450 avis cumulés)
      → 7 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   📄 Page 47  (457 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 48  (467 avis cumulés)
      → 9 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   📄 Page 49  (476 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   📄 Page 50  (486 avis cumulés)
      → 10 nouveaux avis
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 1/3
   ⚠️  Contenu inchangé après 30s (tentative 1/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 2/3
   ⚠️  Contenu inchangé après 30s (tentative 2/3)
   🔄 Nouvelle tentative dans 3s...
      🔘 Bouton trouvé : 'Page suivante'
      ✅ Clic OK (normal) — tentative 3/3
   ⚠️  Contenu inchangé après 30s (tentative 3/3)
   ❌ Échec après 3 tentatives.
   ✅ Dernière page atteinte.

✅ 496 avis extraits au total

💾 Fichier sauvegardé : avis_Ibis_El_Jadida.csv  (496 avis)

🔍 Aperçu :
  reviewer_name nationality rating            trip_type                        publication_date      stay_date language
0           Lam       Maroc    7.0  Voyageur individuel     Commentaire envoyé le 15 avril 2026     avril 2026   french
1      Philippe      France    7.0               Couple      Commentaire envoyé le 28 mars 2026      mars 2026   french
2         Tamer       Maroc    6.0              Famille      Commentaire envoyé le 23 mars 2026      mars 2026   french
3           Ait       Maroc    6.0  Voyageur individuel   Commentaire envoyé le 26 février 2026   février 2026   french
4      Ridouane       Maroc    7.0  Voyageur individuel   Commentaire envoyé le 16 février 2026   février 2026   french
5     Chehouani       Maroc    8.0               Couple    Commentaire envoyé le 5 février 2026   janvier 2026   french
6         Rahim      France    7.0              Famille   Commentaire envoyé le 11 janvier 2026   janvier 2026   french
7         Hamza       Maroc    7.0  Voyageur individuel  Commentaire envoyé le 14 décembre 2025  décembre 2025   french
8        Azdine       Maroc    7.0              Famille  Commentaire envoyé le 14 décembre 2025  décembre 2025   french
9         Sanae       Maroc    6.0  Voyageur individuel   Commentaire envoyé le 8 décembre 2025  décembre 2025   french

📊 Colonnes vides :
  Aucune colonne vide 🎉

In [22]:
df.columns

Index(['source', 'hotel_name', 'hotel_city', 'reviewer_name', 'nationality',
       'rating', 'review_title', 'review_text', 'positive_comment',
       'negative_comment', 'publication_date', 'stay_date', 'trip_type',
       'language'],
      dtype='str')

In [1]:
import pandas as pd

files = [
    "avis_Ibis_Casablanca_Abdelmoumen_booking.csv",
    "avis_Ibis_Casablanca_City_Center_booking.csv",
    "avis_Ibis_Casablanca_Nearshore_booking.csv",
    "avis_Ibis_Casablanca_Sidi_Maarouf_booking.csv",
    "avis_Ibis_Casablanca_Voyageurs_booking.csv",
    "avis_Ibis_El_Jadida_booking.csv",
    "avis_Ibis_Marrakech_Centre_Gare_booking.csv",
    "avis_Ibis_Marrakech_Palmeraie_booking.csv",
    "avis_Ibis_Meknes_booking.csv",
    "avis_Ibis_Mohammedia_booking.csv",
    "avis_Ibis_Moussafir_Fès_booking.csv",
    "avis_Ibis_Ouarzazate_booking.csv",
    "avis_Ibis_Oujda_booking.csv",
    "avis_Ibis_Rabat_Agdal_booking.csv",
    "avis_Ibis_Tanger_City_Center_booking.csv",
]

Avis_booking_total = pd.concat(
    [pd.read_csv(f) for f in files], ignore_index=True
)

print(f"Shape : {Avis_booking_total.shape}")
print(Avis_booking_total.head())

Avis_booking_total.to_csv("Avis_booking_total.csv", index=False)
print("Sauvegardé ✓")

Shape : (14771, 14)
        source                   hotel_name  hotel_city reviewer_name  \
0  booking.com  Ibis Casablanca Abdelmoumen  Casablanca         Edris
1  booking.com  Ibis Casablanca Abdelmoumen  Casablanca        Samata
2  booking.com  Ibis Casablanca Abdelmoumen  Casablanca        Tasnim
3  booking.com  Ibis Casablanca Abdelmoumen  Casablanca         Asmaa
4  booking.com  Ibis Casablanca Abdelmoumen  Casablanca          Adda

  nationality  rating                                       review_title  \
0       Maroc     7.0                                               Bien
1      France     7.0                                               Bien
2      France     8.0                     Excellent rapport qualité prix
3       Maroc     7.0  Un personnel agréable et un très bn rapport qu...
4       Maroc     8.0                                              حميلة

                                         review_text  \
0                                         Tout Bruit
1  Hôtel à proximité vraiment de tout , propre et...
2  Chambre spacieuse, hôtel moderne et personnel ...
3  Situation géographique Il y a du bruit vu just...
4                                      نعن تمن مرتفع

                                    positive_comment  \
0                                               Tout
1  Hôtel à proximité vraiment de tout , propre et...
2  Chambre spacieuse, hôtel moderne et personnel ...
3                             Situation géographique
4                                                نعن

                             negative_comment  \
0                                       Bruit
1             Dommage le lit est dure !!!!!!!
2                                         NaN
3  Il y a du bruit vu justement l'emplacement
4                                   تمن مرتفع

                      publication_date   stay_date            trip_type  \
0  Commentaire envoyé le 22 avril 2026  avril 2026  Voyageur individuel
1  Commentaire envoyé le 14 avril 2026  avril 2026              Famille
2  Commentaire envoyé le 11 avril 2026  avril 2026  Voyageur individuel
3   Commentaire envoyé le 5 avril 2026   mars 2026  Voyageur individuel
4   Commentaire envoyé le 29 mars 2026   mars 2026  Voyageur individuel

  language
0   french
1   french
2   french
3   french
4   arabic
Sauvegardé ✓

In [2]:
Avis_booking_total.head()

,source,hotel_name,hotel_city,reviewer_name,nationality,rating,review_title,review_text,positive_comment,negative_comment,publication_date,stay_date,trip_type,language
0,booking.com,Ibis Casablanca Abdelmoumen,Casablanca,Edris,Maroc,7.0,Bien,Tout Bruit,Tout,Bruit,Commentaire envoyé le 22 avril 2026,avril 2026,Voyageur individuel,french
1,booking.com,Ibis Casablanca Abdelmoumen,Casablanca,Samata,France,7.0,Bien,"Hôtel à proximité vraiment de tout , propre et...","Hôtel à proximité vraiment de tout , propre et...",Dommage le lit est dure !!!!!!!,Commentaire envoyé le 14 avril 2026,avril 2026,Famille,french
2,booking.com,Ibis Casablanca Abdelmoumen,Casablanca,Tasnim,France,8.0,Excellent rapport qualité prix,"Chambre spacieuse, hôtel moderne et personnel ...","Chambre spacieuse, hôtel moderne et personnel ...",NaN,Commentaire envoyé le 11 avril 2026,avril 2026,Voyageur individuel,french
3,booking.com,Ibis Casablanca Abdelmoumen,Casablanca,Asmaa,Maroc,7.0,Un personnel agréable et un très bn rapport qu...,Situation géographique Il y a du bruit vu just...,Situation géographique,Il y a du bruit vu justement l'emplacement,Commentaire envoyé le 5 avril 2026,mars 2026,Voyageur individuel,french
4,booking.com,Ibis Casablanca Abdelmoumen,Casablanca,Adda,Maroc,8.0,حميلة,نعن تمن مرتفع,نعن,تمن مرتفع,Commentaire envoyé le 29 mars 2026,mars 2026,Voyageur individuel,arabic

In [3]:
Avis_booking_total.columns

Index(['source', 'hotel_name', 'hotel_city', 'reviewer_name', 'nationality',
       'rating', 'review_title', 'review_text', 'positive_comment',
       'negative_comment', 'publication_date', 'stay_date', 'trip_type',
       'language'],
      dtype='str')